apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    
spec:
    replicas: 1
    selector:
        matchLabels:
            component: api
    template: 
        metadata:
            labels:
                component: api
        spec:
            containers:
              - name: api
                image: shrikaan038/m2project-nov:latest
                ports:
                    - containerPort: 3000
                env:
                    - name: POSTGRES_USER
                      value: postgres
                    - name: POSTGRES_HOST
                      value: postgres-cluster-ip-service
                    - name: POSTGRES_DB
                      value: simple_blog_api
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            key: POSTGRES_PASSWORD
                            name: pgpassword
                    
                     